apiVersion: v1
clusters:
- cluster:
    certificate-authority-data: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURKekNDQWcrZ0F3SUJBZ0lDQm5Vd0RRWUpLb1pJaHZjTkFRRUxCUUF3TXpFVk1CTUdBMVVFQ2hNTVJHbG4KYVhSaGJFOWpaV0Z1TVJvd0dBWURWUVFERXhGck9ITmhZWE1nUTJ4MWMzUmxjaUJEUVRBZUZ3MHlNekF6TVRneApOekV4TkRKYUZ3MDBNekF6TVRneE56RXhOREphTURNeEZUQVRCZ05WQkFvVERFUnBaMmwwWVd4UFkyVmhiakVhCk1CZ0dBMVVFQXhNUmF6aHpZV0Z6SUVOc2RYTjBaWElnUTBFd2dnRWlNQTBHQ1NxR1NJYjNEUUVCQVFVQUE0SUIKRHdBd2dnRUtBb0lCQVFDcmg3M25IWmVPQ09vWklQczBmQ2Q5MFBmYTdWSGxNdWhaS1V1alhsbUgyd2R1U1prTQpQS2NLdmhRUitTdncxRlQxNEdhWXZHcHVGSStvSVlVazJDeE1NQVJlNmVKYWgvQS90Wm9ub1RnVDNDZ2FmWE9rCml2TXRpUmtjUXBUU2ZoVVl3TVpDdTczVHZZMlJLemtESGFUS1hkWkFUMVV6R2FId0FIUmNkeGdpMTVaT2diTmwKSEREcXAwcTdBczc2dUtTVWw5UzlGWGpYbTVMdUdBYXMvY0JaOFR4UjNTNTR3T0I5QUFDTkppb3hyV3BHWE9MYgpyVkgwV1JOVVM4MEs2dW9iZlM1Tlo1bkF6d09LTUI0aVpjR0xVNjhOOGp2RXVuYjh5a0NqS3owK29IVmU2QTNXCjZiSXRuZmdjWm50MTZ1N2N1NDNkNXBua2EwV3NWZE5rWmNRTkFnTUJBQUdqUlRCRE1BNEdBMVVkRHdFQi93UUUKQXdJQmhqQVNCZ05WSFJNQkFmOEVDREFHQVFIL0FnRUFNQjBHQTFVZERnUVdCQlJ0Ui92aWNJRjF5QXh5d3VQTQpnSGRWOVhLZ2t6QU5CZ2txaGtpRzl3MEJBUXNGQUFPQ0FRRUFCU0NmVFAwSG0xSDdCZmI5NWNQalpad3VkNUZvCjczUHpJc0plS3owNUlJa1pUWkFRTDBubVpOLzAxRU16bkNlWjk2NFA0cWdFMFE2TnFNSHlKNUtvaWlhU2xVcDcKV1hkUkJieXIwakpQaTdwL1JjamVIbmZkS2R3VUdsSmhrYmdKdVQzT2ZpK3V2bDlXT3U5VkFpdlk0bjZzblJoSwpWZmFQVnRrWDA0UkhRdFQydjNDYWpjTlQzRzZqSUo0azV0M0ErMENEbmJHZDloajAyMjRDcGlncCtyUUhmTm82Cld4a0lwb2RsSERXY09rZXJMeG5xekx6c0tEaHg0OUZLYXRCN3BLTGtpN21kOU5tLzVFRldDd3RoWWg2VlhHczEKaWo3c1MrQnhRRk93UzlubzF6L0M2cEE0clBrUEM3TndQeitlZDZ3akRVMm1EOXArK3dVNTRBdk9KQT09Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K
    server: https://b3f69e8b-dcfc-4427-9807-f078d77cbc09.k8s.ondigitalocean.com
  name: do-lon1-altschool-kubernetes-cluster
contexts:
- context:
    cluster: do-lon1-altschool-kubernetes-cluster
    user: do-lon1-altschool-kubernetes-cluster-admin
  name: do-lon1-altschool-kubernetes-cluster
current-context: do-lon1-altschool-kubernetes-cluster
kind: Config
preferences: {}
users:
- name: do-lon1-altschool-kubernetes-cluster-admin
  user:
    exec:
      apiVersion: client.authentication.k8s.io/v1beta1
      args:
      - kubernetes
      - cluster
      - kubeconfig
      - exec-credential
      - --version=v1beta1
      - --context=default
      - b3f69e8b-dcfc-4427-9807-f078d77cbc09
      command: doctl
      env: null
      provideClusterInfo: false
